server:
  port: 0
spring:
  boot:
   admin:
    client:
     url: http://localhost:8088
  application:
    name: house-hold-client-service
eureka:
  instance:
    instance-id: =${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS
