eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
server:
  port: 9090
spring:
  boot:
   admin:
    client:
     url: http://localhost:8088
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: lb://ACCOUNT-SERVICE/
        predicates:
        - Path=/accounts/**
      - id: customerModule
        uri: lb://CUSTOMER-SERVICE/
        predicates:
        - Path=/customers/**
      - id: productModule
        uri: lb://PRODUCT-SERVICE/
        predicates:
        - Path=/products/**